### ISSUE TITLE
Nativescript-Angular Error

### ISSUE THREAD

**Issue by betov18x** [championswimmer/nativescript-vue-typeorm-sample#1]
I'm trying to use this sample code in a nativescript-angular project but when i run the project i get the next error: 

`JS: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save`

But i do have the package installed it is in my node_modules. 

Also in the main.ts i have this error:

`ERROR in app/main.ts(23,51): error TS2345: Argument of type '{ database: string; type: "nativescript"; entities: (typeof Todo)[]; logging: true; }' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ database: string; type: "nativescript"; entities: (typeof Todo)[]; logging: true; }' is not assignable to type 'NativescriptConnectionOptions'.
    Property 'driver' is missing in type '{ database: string; type: "nativescript";entities: (typeof Todo)[]; logging: true; }'.`

This is my code:
```

import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { AppModule } from "./app.module";
import { registerElement } from "nativescript-angular/element-registry";

// Validators
import { EmailValidator } from "~/validators/email.validator";
import { RequiredValidator } from "~/validators/required.validator";

registerElement("Fab", () => require("nativescript-floatingactionbutton").Fab);
registerElement('AnimatedCircle', () => require('nativescript-animated-circle').AnimatedCircle);

// Validators register
registerElement('EmailValidator', () => <any>EmailValidator);
registerElement('RequiredValidator', () => <any>RequiredValidator);

//TypeORM
import {createConnection, getManager} from 'typeorm/browser';
import { Todo } from './entities/Todo';

(async () => {
    try {
        const connection = await createConnection({
            database: './test.db',
            type: 'nativescript',
            entities: [
                Todo
            ],
            logging: true
        })

        console.log("Connection Created");

        // setting true will drop tables and recreate
        await connection.synchronize(true); 

        console.log("Synchronized");


    } catch (err) {
        console.log("Error");
        console.error(err);
    }
})();


platformNativeScriptDynamic().bootstrapModule(AppModule);
```

**Comment by championswimmer** [comment]
Oh I am so sorry I didn't update the README. you need to pass the driver along with the type now. 

```ts
import driver from 'nativescript-sqlite'

const connection = await createConnection({
    database: 'test.db',
    type: 'nativescript',
    driver, // <------- that 
    entities: [
        Todo //... whatver entities you have
    ],
    logging: true
})
```

**Comment by betov18x** [comment]
Thank's problem fixed.
`let driver = require('nativescript-sqlite');`
